serviceHostname: localhost
serviceListenPort: 8001
controlHostname: localhost
controlListenPort: 8002
agentHostname: localhost
agentListenPort: 8003
caConfig:
  caCertFile: ca-cert.pem
  caKeyFile: ca-key.pem
serviceAuth:
  currentKeyName: key1
  headerMutationKeyName: key2
  secretsPath: not-actually
services:
  outgoingServices:
    - name: whoami
      type: whoami
      enabled: true
      config:
        url: http://localhost:8300
  incomingServices:
    - name: agent-whoami
      serviceType: whoami
      port: 8011
      useHTTP: true
      destination: smith
      destinationService: whoami
    - name: agent-whoami-loop
      serviceType: whoami
      port: 8012
      useHTTP: true
      destination: smith
      destinationService: whoami-loop
    - name: controller-nosuchsercvice
      serviceType: x-notthere
      port: 8013
      useHTTP: true
      destination: nosuchagent
      destionalService: controller-nosuchservice
