serviceHostname: localhost
serviceListenPort: 8001
controlHostname: localhost
controlListenPort: 8002
agentHostname: localhost
agentListenPort: 8003
serviceAuth:
  currentKeyName: key1
  servicesConfigPath: key2
  secretsPath: not-actually
services:
  outgoingServices:
    - name: whoami
      type: whoami
      enabled: true
      config:
        url: http://localhost:8300
  incomingServices:
    - name: agent-whoami
      serviceType: whoami
      port: 8004
      destination: smith
      destinationService: whoami
    - name: agent-whoami-loop
      serviceType: whoami
      port: 8005
      destination: smith
      destinationService: whoami-loop
