agentInfo:
  annotations:
    description: demo agent
outgoingServices:
  - name: whoami
    type: whoami
    enabled: true
    config:
      url: https://whoami.svc.rpi.flame.org
    annotations:
      description: Whoami on my raspberry pi cluster of doom!
incomingServices:
  - name: controller-whoami
    serviceType: whoami
    port: 8014
    destination: controller
    destinationService: whoami
  - name: controller-nosuchservice
    serviceType: x-notthere
    port: 8015
    destination: controller
    destionalService: controller-nosuchservice
