outgoingServices:
  - name: whoami
    type: whoami
    enabled: true
    config:
      url: http://localhost:8300
  - name: whoami-loop
    type: whoami
    enabled: true
    config:
      url: http://localhost:8006 # loop back to our own port here
incomingServices:
  - name: controller-whoami
    serviceType: whoami
    port: 8006
    destination: controller
    destinationService: whoami
