name: Docker Image CI

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      id: buildx
    - name: Inspect builder
      run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
    - name: Login to docker
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_FLAME_HOSTNAME }}
        username: ${{ secrets.DOCKER_FLAME_USERNAME }}
        password: ${{ secrets.DOCKER_FLAME_PASSWORD }}
    - name: Build the Docker image
      run: make images
