name: Docker Image CI

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      id: buildx
    - name: Inspect builder
      run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
    - name: Login to docker
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_PUBLIC_HOSTNAME }}
        username: ${{ secrets.DOCKER_PUBLIC_USERNAME }}
        password: ${{ secrets.DOCKER_PUBLIC_PASSWORD }}
    - name: Build the Docker image
      id: dockerbuild
      run: make IMAGE_PREFIX=quay.io/opsmxpublic/ clean images image-names
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BUILD_EVENTS_WEBHOOK_URL }}
      with:
        payload: |
          {
            "imageNames": "${{ steps.dockerbuild.outputs.imageNames }}",
            "actor": "${{ github.actor }}",
            "status": "${{ job.status }}"
          }
